// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aeoper101/kratos-layout/internal/biz"
	"github.com/aeoper101/kratos-layout/internal/conf"
	"github.com/aeoper101/kratos-layout/internal/data"
	"github.com/aeoper101/kratos-layout/internal/i18n"
	"github.com/aeoper101/kratos-layout/internal/server"
	"github.com/aeoper101/kratos-layout/internal/service"
	"github.com/aesoper101/kratos-utils/protobuf/types/confpb"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *confpb.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterLogic := biz.NewGreeterLogic(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterLogic)
	services := &service.Services{
		GreeterService: greeterService,
	}
	i18nBundle, err := i18n.NewI18nBundle()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(confServer, services, i18nBundle, logger)
	grpcServer := server.NewGRPCServer(confServer, services, i18nBundle, logger)
	app := newApp(logger, httpServer, grpcServer, registry)
	return app, func() {
		cleanup()
	}, nil
}
